// Firebase configuration for the Service Centre app.
//
// NORMALLY generated by `flutterfire configure`, but this project has no local
// Flutter toolchain (see HANDOFF.md "operating model"), so it is hand-written
// from the values in the owner's `google-services.json`.
//
// ── HOW TO FILL THIS IN (Phase 2) ────────────────────────────────────────────
// The owner creates a Firebase project, registers an Android app with package
// `com.saagar.service_centre_app`, and downloads `google-services.json`. Map its
// fields to the `android` options below (the JSON has ONE `client` entry for our
// package — use that one):
//
//   FirebaseOptions field   ←  google-services.json path
//   ----------------------     -----------------------------------------------
//   apiKey                  ←  client[0].api_key[0].current_key
//   appId                   ←  client[0].client_info.mobilesdk_app_id
//   messagingSenderId       ←  project_info.project_number
//   projectId               ←  project_info.project_id
//   storageBucket           ←  project_info.storage_bucket
//
// Verify client[0].client_info.android_client_info.package_name reads exactly
// `com.saagar.service_centre_app` before copying values. Replace every
// `[PLACEHOLDER ...]` string below, delete the `_isPlaceholder` guard note, and
// commit. No `google-services.json` file is needed in the repo — FlutterFire
// reads these Dart values directly (the Android build does not apply the
// com.google.gms.google-services Gradle plugin).
//
// App Check stays on the debug provider with enforcement OFF for the pilot
// (see lib/bootstrap/bootstrap.dart).
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for the current platform.
///
/// The pilot ships Android only; other platforms are intentionally
/// unconfigured and throw [UnsupportedError] if reached.
class DefaultFirebaseOptions {
  /// Firebase options for the platform the app is currently running on.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions are not configured for web. '
        'The pilot targets Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for $defaultTargetPlatform. '
          'The pilot targets Android only.',
        );
    }
  }

  /// Android options, hand-written from the owner's `google-services.json`.
  ///
  /// [PLACEHOLDER] Until the five values below are replaced with the real ones,
  /// `Firebase.initializeApp` fails at runtime; `bootstrap()` tolerates that and
  /// the app still boots to the login screen (it just cannot authenticate).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '[PLACEHOLDER apiKey — client[0].api_key[0].current_key]',
    appId: '[PLACEHOLDER appId — client[0].client_info.mobilesdk_app_id]',
    messagingSenderId:
        '[PLACEHOLDER messagingSenderId — project_info.project_number]',
    projectId: '[PLACEHOLDER projectId — project_info.project_id]',
    storageBucket: '[PLACEHOLDER storageBucket — project_info.storage_bucket]',
  );
}
