// GENERATED FILE — PLACEHOLDER. Do not rely on this in production.
//
// Replace by running:  flutterfire configure
// This stub lets the project compile before Firebase is configured. At runtime,
// bootstrap() (lib/bootstrap/bootstrap.dart) tolerates the missing config so the
// app still boots to its placeholder home during M0.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase options. [PLACEHOLDER — flutterfire configure]
class DefaultFirebaseOptions {
  /// Throws until real options are generated by `flutterfire configure`.
  static FirebaseOptions get currentPlatform => throw UnimplementedError(
        'firebase_options.dart is a placeholder. '
        'Run `flutterfire configure` to generate the real Firebase config.',
      );
}
