import 'dart:async';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import '../../../../app/l10n/app_localizations.dart';
import '../../../auth/presentation/auth_guard.dart';
import '../../../auth/presentation/providers/staff_providers.dart';
import '../providers/backup_providers.dart';

/// Owner-only local backup screen. The generated bytes are also the seam for a
/// future OAuth Drive uploader; no live provider is needed to build or test it.
class BackupScreen extends ConsumerStatefulWidget {
  /// Creates the backup screen.
  const BackupScreen({super.key});

  @override
  ConsumerState<BackupScreen> createState() => _BackupScreenState();
}

class _BackupScreenState extends ConsumerState<BackupScreen> {
  bool _loading = false;

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final branchId = ref.watch(currentBranchIdProvider);
    return Scaffold(
      key: const Key('backupScreen'),
      appBar: AppBar(
        title: Text(l10n.backupTitle),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.go(Routes.home),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(l10n.backupDescription),
            const SizedBox(height: 16),
            FilledButton.icon(
              key: const Key('createBackupBtn'),
              onPressed: branchId == null || _loading
                  ? null
                  : () => unawaited(_createBackup(branchId)),
              icon: _loading
                  ? const SizedBox.square(
                      dimension: 18,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.download_outlined),
              label: Text(l10n.backupCreate),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _createBackup(String branchId) async {
    final l10n = AppLocalizations.of(context);
    final messenger = ScaffoldMessenger.of(context);
    setState(() => _loading = true);
    final result = await ref
        .read(backupRepositoryProvider)
        .buildBranchBackup(branchId);
    if (!mounted) return;
    setState(() => _loading = false);
    final file = result.valueOrNull;
    if (file == null) {
      messenger.showSnackBar(SnackBar(content: Text(l10n.backupFailed)));
      return;
    }
    final path = await FilePicker.platform.saveFile(
      fileName: file.fileName,
      bytes: file.bytes,
    );
    messenger.showSnackBar(
      SnackBar(
        content: Text(path == null ? l10n.backupCancelled : l10n.backupSaved),
      ),
    );
  }
}
